controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  - name: "gripper_actions"
    action_ns: gripper_command
    type: GripperCommand
    default: true   
    command_joint: gripper_finger1_joint
    joints:
      - gripper_finger1_joint
   
        
        

